/**
 * Builds sql/scenario2-streaks/seed.sql from the API's dataset (api/data/players.json,
 * matches.json) plus the streak innings (sql/scenario2-streaks/innings.json), so the API and the
 * SQL scenario share one source of truth.
 *
 *   npm run sql:seed     # regenerate seed.sql
 *
 * tests/sql/streaks.spec.ts fails if the committed seed.sql differs from what this produces.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(__dirname, '..', '..');
export const SEED_PATH = path.join(root, 'sql', 'scenario2-streaks', 'seed.sql');

interface Player {
  id: number;
  name: string;
  teamId: string;
}
interface Match {
  id: number;
  season: number;
  date: string;
  stage: string;
  venue: string;
  homeTeamId: string;
  awayTeamId: string;
  winnerTeamId: string | null;
}
interface Innings {
  matchId: number;
  playerId: number;
  runs: number;
  balls: number;
  notOut: boolean;
}

const readJson = <T>(...segments: string[]): T =>
  JSON.parse(readFileSync(path.join(root, ...segments), 'utf8')) as T;

const text = (value: string) => `'${value.replace(/'/g, "''")}'`;
const nullable = (value: string | null) => (value === null ? 'NULL' : text(value));

export function buildIplSeed(): string {
  const players = readJson<Player[]>('api', 'data', 'players.json');
  const matches = readJson<Match[]>('api', 'data', 'matches.json');
  const { abandonedMatchIds, extraMatches, innings } = readJson<{
    abandonedMatchIds: number[];
    extraMatches: Match[];
    innings: Innings[];
  }>('sql', 'scenario2-streaks', 'innings.json');
  const allMatches = [...matches, ...extraMatches].sort((a, b) => a.id - b.id);

  const playerRows = players.map((p) => `(${p.id}, ${text(p.name)}, ${text(p.teamId)})`);
  const matchRows = allMatches.map(
    (m) =>
      `(${m.id}, ${m.season}, ${text(m.date)}, ${text(m.stage)}, ${text(m.venue)}, ` +
      `${text(m.homeTeamId)}, ${text(m.awayTeamId)}, ${nullable(m.winnerTeamId)}, ${abandonedMatchIds.includes(m.id)})`,
  );
  const inningsRows = innings.map(
    (i) => `(${i.matchId}, ${i.playerId}, ${i.runs}, ${i.balls}, ${i.notOut})`,
  );

  return [
    '-- Scenario 2 seed. GENERATED by `npm run sql:seed` from api/data/*.json and',
    '-- sql/scenario2-streaks/innings.json. Do not edit by hand.',
    '-- Illustrative IPL-2024-style sample data, not official statistics.',
    '',
    'INSERT INTO players (player_id, player_name, team_id) VALUES',
    playerRows.join(',\n') + ';',
    '',
    'INSERT INTO matches (match_id, season, match_date, stage, venue, home_team, away_team, winner_team, abandoned) VALUES',
    matchRows.join(',\n') + ';',
    '',
    'INSERT INTO batting_scores (match_id, player_id, runs, balls_faced, is_not_out) VALUES',
    inningsRows.join(',\n') + ';',
    '',
  ].join('\n');
}

if (require.main === module) {
  writeFileSync(SEED_PATH, buildIplSeed(), 'utf8');
  console.log(`Wrote ${path.relative(root, SEED_PATH)}`);
}
